package com.bankstack.mcp.safety;

public enum ToolCategory {
    ACCOUNT_INFORMATION,
    TRANSACTION_HISTORY,
    CUSTOMER_PROFILE,
    PAYMENT_ACTION,
    PAYMENT_STATUS,
    FRAUD_CONTROL,
    DISPUTE_ACTION,
    TRANSFER_ACTION,
    ADMIN_OPERATION,
    INTERNAL_SUPPORT,
    KNOWLEDGE_RETRIEVAL,
    RAG
}