server:
  port: 8094

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-4mxqf6pdu0czpsbp.us.auth0.com/}
  application:
    name: auth-user


logging:
  level:
    root: INFO
    com.authuser: DEBUG
    org.springframework.security: DEBUG
    

    
    
consent:
  service:
    url: http://localhost:8096/api/v1
    
    
auth0:
  domain: ${AUTH0_DOMAIN:https://dev-4mxqf6pdu0czpsbp.us.auth0.com}
  audience: ${AUTH0_AUDIENCE:https://mockbank/api}
  mgmt:
     client-id: ${AUTH0_MGMT_CLIENT_ID}
     client-secret: ${AUTH0_MGMT_CLIENT_SECRET}
     audience: ${AUTH0_DOMAIN:https://dev-4mxqf6pdu0czpsbp.us.auth0.com}/api/v2/