server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-4mxqf6pdu0czpsbp.us.auth0.com/}
  application:
    name: biller-service


  datasource:
    url: jdbc:postgresql://localhost:5432/billerdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG

    
    
auth0:
  audience: ${AUTH0_AUDIENCE:https://mockbank/api}
