# Generated for module BillPayWorkerService
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billpay-worker
  namespace: bankstack
  labels:
    app: billpay-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billpay-worker
  template:
    metadata:
      labels:
        app: billpay-worker
    spec:
      containers:
        - name: billpay-worker
          image: bankstack/billpay-worker:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/billpayworkerdb"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 768Mi
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 90
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: billpay-worker
  namespace: bankstack
spec:
  selector:
    app: billpay-worker
  ports:
    - port: 8090
